version: '3.8'
services:
  mariadb:
    image: mariadb:10.9
    restart: always
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: quarkus
      MARIADB_USER: quarkus
      MARIADB_PASSWORD: quarkus
    ports:
      - "3306:3306"