version: '3.8'
services:

  app:
    build: .
    restart: always
    ports:
      - "8080:8080"

  mariadb:
    image: mariadb:10.9
    restart: always
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: hauptchemicals
      MARIADB_USER: hauptchemicals
      MARIADB_PASSWORD: hauptchemicals
    ports:
      - "3306:3306"