version: '3.8'
services:
  mariadb:
    image: mariadb:10.9
    restart: always
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: haupt-chemicals
      MARIADB_USER: haupt-chemicals
      MARIADB_PASSWORD: haupt-chemicals
    ports:
      - "3306:3306"