insert into hauptchemicals.pr_product(pr_id, pr_titel, pr_created_at, pr_content, pr_updated_at)
values(1, "Maleinsäureanhydrid", now(), "(MSA)", now()),
(2, "Phthalsäureanhydrid", now(), "(PSA)", now()),
(3, "Trimellitsäureanhydrid", now(), "(TMA)", now()),
(4, "Hexahydrophthalsäureanhydrid", now(), "(HHPA)", now()),
(5, "Methylhexahydrophthalsäureanhydrid", now(), "(MHHPA)", now()),
(6, "Monoethanolamin", now(), "85% W", now()),
(7, "Monoethanolamin", now(), "99,4%", now()),
(8, "Triethanolamin", now(), "85%", now()),
(9, "Triethanolamin", now(), "85% W", now()),
(10, "Triethanolamin", now(), "99%", now()),
(11, "Diethylenglykol ", now(), "(DEG)", now()),
(12, "1,2-Propandiol", now(), "(MPG)", now()),
(13, "Neopentylglykol ", now(), "(NPG)", now()),
(14, "1,10-Decandiol", now(), "", now()),
(15, "HDI Biureth", now(), "", now()),
(16, "HDI Trimer", now(), "", now()),
(17, "HDI Geblockt", now(), "", now()),
(18, "HDI Wässrig", now(), "", now()),
(19, "TDI TMP", now(), "", now()),
(20, "Caprylsäure", now(), "(C8)", now()),
(21, "Laurinsäure", now(), "(C12)", now()),
(22, "Stearinsäure", now(), "(C16-18)", now()),
(23, "Ölsäure", now(), "(C16-18)", now()),
(24, "Palmkernfettsäure ", now(), "(C12-18)", now()),
(25, "Sequestrant", now(), "(HEDP)", now()),
(26, "Sequestrant", now(), "(HEDPNa4 G)", now()),
(27, "Sequestrant", now(), "(PBTC)", now()),
(28, "Sequestrant", now(), "(ATMP)", now()),
(29, "Sequestrant", now(), "(DTPMPNa7)", now()),
(30, "Sequestrant", now(), "(GLDANa4)", now()),
(31, "Sequestrant", now(), "(MDGA)", now()),
(32, "Silikonöl", now(), "(100)", now()),
(33, "Silikonöl", now(), "(1000)", now()),
(34, "Silikonöl", now(), "(10000)", now()),
(35, "Silikonöl", now(), "(12500)", now()),
(36, "Silikonöl", now(), "(350)", now()),
(37, "Silikonöl", now(), "(5000)", now()),
(38, "Silikonöl", now(), "(C4)", now()),
(39, "Silikonöl", now(), "(C5)", now()),
(40, "Silikonöl", now(), "(C6)", now()),
(41, "Silikonöl", now(), "(BC5DL)", now()),
(42, "Propionat", now(), "(80)", now()),
(43, "Betain", now(), "(30)", now()),
(44, "Betain", now(), "(40)", now()),
(45, "Methylphosphat", now(), "", now()),
(46, "Butylphosphat", now(), "", now()),
(47, "Octylphosphat", now(), "", now()),
(48, "Laurylsulfat", now(), "", now()),
(49, "Laurylethersulfat", now(), "", now()),
(50, "Sulfosuccinate", now(), "", now()),
(51, "Sulfonsäure", now(), "", now()),
(52, "Sulfonat", now(), "", now()),
(53, "Alkylpolyglykoside", now(), "", now()),
(54, "Cocamide", now(), "", now()),
(55, "C10 FA", now(), "(8 EO)", now()),
(56, "C11 FA", now(), "(6 EO)", now()),
(57, "C12 FA", now(), "(14 EO)", now()),
(58, "C16 FA", now(), "(7 EO)", now()),
(59, "C14 FA", now(), "(4 EO)", now()),
(60, "C16 FA", now(), "(25)", now()),
(61, "Glycerin", now(), "(11 EO)", now()),
(62, "Talgamin", now(), "(10 EO)", now()),
(63, "Rizinusöl", now(), "(55 EO)", now()),
(64, "Rizinusöl", now(), "(35 EO)", now()),
(65, "Rizinusöl", now(), "(20 EO)", now()),
(66, "Halupox", now(), "(RVM 214)", now()),
(67, "Halupox", now(), "(RVM 256)", now()),
(68, "Zitronensäure monohydrat", now(), "", now()),
(69, "Trinatriumcitrat", now(), "", now()),
(70, "Tricalciumcitrat", now(), "", now())
;