insert into hauptchemicals.pr_product(pr_id, pr_titel, pr_created_at, pr_quantity, pr_content, pr_updated_at)
values(1, "Maleinsäureanhydrid", now(), 0, "(MSA)", now()),
(2, "Phthalsäureanhydrid", now(), 0, "(PSA)", now()),
(3, "Trimellitsäureanhydrid", now(), 0, "(TMA)", now()),
(4, "Hexahydrophthalsäureanhydrid", now(), 0, "(HHPA)", now()),
(5, "Methylhexahydrophthalsäureanhydrid", now(), 0, "(MHHPA)", now()),
(6, "Monoethanolamin", now(), 0, "85% W", now()),
(7, "Monoethanolamin", now(), 0, "99,4%", now()),
(8, "Triethanolamin", now(), 0, "85%", now()),
(9, "Triethanolamin", now(), 0, "85% W", now()),
(10, "Triethanolamin", now(), 0, "99%", now()),
(11, "Diethylenglykol ", now(), 0, "(DEG)", now()),
(12, "1,2-Propandiol", now(), 0, "(MPG)", now()),
(13, "Neopentylglykol ", now(), 0, "(NPG)", now()),
(14, "1,10-Decandiol", now(), 0, "", now()),
(15, "HDI Biureth", now(), 0, "", now()),
(16, "HDI Trimer", now(), 0, "", now()),
(17, "HDI Geblockt", now(), 0, "", now()),
(18, "HDI Wässrig", now(), 0, "", now()),
(19, "TDI TMP", now(), 0, "", now()),
(20, "Caprylsäure", now(), 0, "(C8)", now()),
(21, "Laurinsäure", now(), 0, "(C12)", now()),
(22, "Stearinsäure", now(), 0, "(C16-18)", now()),
(23, "Ölsäure", now(), 0, "(C16-18)", now()),
(24, "Palmkernfettsäure ", now(), 0, "(C12-18)", now()),
(25, "Sequestrant", now(), 0, "(HEDP)", now()),
(26, "Sequestrant", now(), 0, "(HEDPNa4 G)", now()),
(27, "Sequestrant", now(), 0, "(PBTC)", now()),
(28, "Sequestrant", now(), 0, "(ATMP)", now()),
(29, "Sequestrant", now(), 0, "(DTPMPNa7)", now()),
(30, "Sequestrant", now(), 0, "(GLDANa4)", now()),
(31, "Sequestrant", now(), 0, "(MDGA)", now()),
(32, "Silikonöl", now(), 0, "(100)", now()),
(33, "Silikonöl", now(), 0, "(1000)", now()),
(34, "Silikonöl", now(), 0, "(10000)", now()),
(35, "Silikonöl", now(), 0, "(12500)", now()),
(36, "Silikonöl", now(), 0, "(350)", now()),
(37, "Silikonöl", now(), 0, "(5000)", now()),
(38, "Silikonöl", now(), 0, "(C4)", now()),
(39, "Silikonöl", now(), 0, "(C5)", now()),
(40, "Silikonöl", now(), 0, "(C6)", now()),
(41, "Silikonöl", now(), 0, "(BC5DL)", now()),
(42, "Propionat", now(), 0, "(80)", now()),
(43, "Betain", now(), 0, "(30)", now()),
(44, "Betain", now(), 0, "(40)", now()),
(45, "Methylphosphat", now(), 0, "", now()),
(46, "Butylphosphat", now(), 0, "", now()),
(47, "Octylphosphat", now(), 0, "", now()),
(48, "Laurylsulfat", now(), 0, "", now()),
(49, "Laurylethersulfat", now(), 0, "", now()),
(50, "Sulfosuccinate", now(), 0, "", now()),
(51, "Sulfonsäure", now(), 0, "", now()),
(52, "Sulfonat", now(), 0, "", now()),
(53, "Alkylpolyglykoside", now(), 0, "", now()),
(54, "Cocamide", now(), 0, "", now()),
(55, "C10 FA", now(), 0, "(8 EO)", now()),
(56, "C11 FA", now(), 0, "(6 EO)", now()),
(57, "C12 FA", now(), 0, "(14 EO)", now()),
(58, "C16 FA", now(), 0, "(7 EO)", now()),
(59, "C14 FA", now(), 0, "(4 EO)", now()),
(60, "C16 FA", now(), 0, "(25)", now()),
(61, "Glycerin", now(), 0, "(11 EO)", now()),
(62, "Talgamin", now(), 0, "(10 EO)", now()),
(63, "Rizinusöl", now(), 0, "(55 EO)", now()),
(64, "Rizinusöl", now(), 0, "(35 EO)", now()),
(65, "Rizinusöl", now(), 0, "(20 EO)", now()),
(66, "Halupox", now(), 0, "(RVM 214)", now()),
(67, "Halupox", now(), 0, "(RVM 256)", now()),
(68, "Zitronensäure monohydrat", now(), 0, "", now()),
(69, "Trinatriumcitrat", now(), 0, "", now()),
(70, "Tricalciumcitrat", now(), 0, "", now())
;