name: GitHub Actions Feature
on:
  push:
    branches:
      - feature/*
jobs:
  UnitTests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
          cache: 'maven'
      - name: Unit Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test


  mergeMain:
    name: Merge to Main
    runs-on: ubuntu-latest
    needs:
      - UnitTests
    steps:
      - uses: actions/checkout@v2

      - name: merge to main
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: main


  DeleteRemoteFeature:
    name: Delete the Remote Feature

    runs-on: ubuntu-latest
    needs:
      - mergeMain
    steps:
      - name: switch to
        uses: actions/checkout@v2
        with:
          ref: main
      - name: delete the Remote Feature
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: feature/*
          delete-branch: true

  notifyFail:
    name: "Notify Slack Channel #fail"
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs:
      - UnitTests
      - mergeMain
      - DeleteRemoteFeature
    steps:
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}


